### ISSUE TITLE
Booking: Api (Rooms)

### ISSUE THREAD

**Issue by kristianbinau** [HF5-PROJECT/api#19]
Add endpoint for creating, getting, setting and deletion of rooms  - Should be able to return a list of rooms. With image, title, description, size, number, people_amount, hotel_id and id.

* Error handling should be proporly displayed, if any should occur.
* Consider the possibility of an error interface that one or more endpoints could call, for redundancy

Dependent on #27 & #25

**Comment by Anders164a** [comment]
An update has been made to the ER diagram..

Two tables have been added, to define a cleaning status on a room - There are at the moment three statuses for a room; "Not Cleaned", "Missing Towels" & "Cleaning" - Which indicates as soon as someone from the cleaning personel marks a room as Cleaned, the data/room in the table "room_cleaning" should be removed


![Image](https://user-images.githubusercontent.com/27145523/218448271-68d3a76d-d9bf-4b56-a394-414c6c6944b5.png)
